/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhrasesRouteImport } from './routes/phrases'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as A1RouteImport } from './routes/a1'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons_.$lessonId'
import { Route as A1LessonIdRouteImport } from './routes/a1_.$lessonId'

const PhrasesRoute = PhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const A1Route = A1RouteImport.update({
  id: '/a1',
  path: '/a1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons_/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const A1LessonIdRoute = A1LessonIdRouteImport.update({
  id: '/a1_/$lessonId',
  path: '/a1/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/about': typeof AboutRoute
  '/grammar': typeof GrammarRoute
  '/lessons': typeof LessonsRoute
  '/phrases': typeof PhrasesRoute
  '/a1/$lessonId': typeof A1LessonIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/about': typeof AboutRoute
  '/grammar': typeof GrammarRoute
  '/lessons': typeof LessonsRoute
  '/phrases': typeof PhrasesRoute
  '/a1/$lessonId': typeof A1LessonIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/about': typeof AboutRoute
  '/grammar': typeof GrammarRoute
  '/lessons': typeof LessonsRoute
  '/phrases': typeof PhrasesRoute
  '/a1_/$lessonId': typeof A1LessonIdRoute
  '/lessons_/$lessonId': typeof LessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a1'
    | '/about'
    | '/grammar'
    | '/lessons'
    | '/phrases'
    | '/a1/$lessonId'
    | '/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a1'
    | '/about'
    | '/grammar'
    | '/lessons'
    | '/phrases'
    | '/a1/$lessonId'
    | '/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/a1'
    | '/about'
    | '/grammar'
    | '/lessons'
    | '/phrases'
    | '/a1_/$lessonId'
    | '/lessons_/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A1Route: typeof A1Route
  AboutRoute: typeof AboutRoute
  GrammarRoute: typeof GrammarRoute
  LessonsRoute: typeof LessonsRoute
  PhrasesRoute: typeof PhrasesRoute
  A1LessonIdRoute: typeof A1LessonIdRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/phrases': {
      id: '/phrases'
      path: '/phrases'
      fullPath: '/phrases'
      preLoaderRoute: typeof PhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a1': {
      id: '/a1'
      path: '/a1'
      fullPath: '/a1'
      preLoaderRoute: typeof A1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons_/$lessonId': {
      id: '/lessons_/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a1_/$lessonId': {
      id: '/a1_/$lessonId'
      path: '/a1/$lessonId'
      fullPath: '/a1/$lessonId'
      preLoaderRoute: typeof A1LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A1Route: A1Route,
  AboutRoute: AboutRoute,
  GrammarRoute: GrammarRoute,
  LessonsRoute: LessonsRoute,
  PhrasesRoute: PhrasesRoute,
  A1LessonIdRoute: A1LessonIdRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
